spring:
  application:
    name: dr-frontend

server:
  port: 8081
  servlet:
    context-path: /dr-frontend

management:
  security:
    enabled: false
  endpoints:
    enabled-by-default: true
    web:
      base-path: /management
      exposure:
        include: "*"